### ISSUE TITLE
docs/app link at the site index is broken

### ISSUE THREAD

**Issue by bebraw** [revolunet/algolia-react-input#3]
Looks like it points to http://blog.revolunet.com/algolia-react-input/#/./docs/app.js . Maybe an absolute link is needed.

**Comment by revolunet** [comment]
HI, thanks for reporting

I dont have this error when visiting http://blog.revolunet.com/algolia-react-input/#/example1 and the example works OK so... how did you get to this error ?

**Comment by bebraw** [comment]
It's that "See complete example in ./docs/app.js" link near bottom of the page.

**Comment by revolunet** [comment]
fixed, thanks !
