### ISSUE TITLE
Not sure what to put into algoliaClient for places searching

### ISSUE THREAD

**Issue by Lutando** [revolunet/algolia-react-input#4]
So I have tried the following

`const algoliaClient = algoliasearch('APPLICATION_ID', 'SEARCH_ONLY_API_KEY');`

and

`const algoliaClient = algoliasearch('places', 'SEARCH_ONLY_API_KEY');`

The former gives me an error because DNS cannot be resolved at 

`http://{APPLICATION_ID}-1.algolianet.com/1...`

The latter gives me 403 / Forbidden because my key may be wrong or something, I may be doing something wrong...
at `http://places-1.algolianet.com/1...`

How do I set up this input client to use algolia places? Thanks for the help and this library :)

**Comment by revolunet** [comment]
Hi
Never played with the Places API so not sure if its compatible or not

**Comment by Lutando** [comment]
oh maybe I was just confused it is compatible with [instantsearch.js](https://community.algolia.com/places/documentation.html#instantsearchjs), I see you're leveraging [algoliasearch](https://github.com/revolunet/algolia-react-input/blob/master/package.json#L83) which doesnt seem to be the same. Late night coding strikes again :)
